[29기 윤남주] JobList 필터링 구현 + 백엔드 통신
wecode-bootcamp-korea/29-2nd-needed-frontend pull request #14
Opened 2022-02-21 11:23 UTC by jujusnake

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 
- 지역 필터링, 정렬기준 변경을 query parameter로 반영하라
- query parameter를 알맞은 백엔드 엔드포인트 api로 변환하여 request를 보내라
- 받은 정보를 잘 렌더링 하여라

<br />

## :: 구현 사항 설명
1. 필터링 모달, 정렬 모달 결정 시 navigate를 통하여 query parameter 변경해주기
- query parameter는 총 3개 : country, location, job_sort

2. 백엔드에 데이터 요청
- 파라미터가 총 5개... category, subcategory, country, location, job_sort
- 경우의 수는 더 많은... 꼭 모두 다 들어오는게 아님....
- 그래서 겁나 복잡한 useEffect가 만들어졌습니다.
- 하지만 나름 탄탄하고 오류가 안날 것 같아요

3. 필터 걸었을 때 개수를 세어서 예쁘게 표시하는 버블 컴포넌트를 만들었다.

<br />

## :: 성장 포인트
- 중간까지 계속 params.search로 받아오고 split, filter, slice로 했었는데 중간부터 진짜 너무 이렇게 하는게 맞는가? 싶었는데
- 찾아보니 URLSearchParams라는 엄청나게 변한 것이 있었습니다...
- axios를 처음으로 써보았습니다!

<br />

## :: 기타 질문 및 특이 사항
- 너무 코드가 어지럽습니다. 혹시 추가구현으로 리팩토링해도 될까요?

2022-02-22 06:42 UTC, younuk23 requested changes
고생하셨습니다 전반적으로 기본적인 부분 조금만 더 다듬으면 될 것 같네요!
전체적으로 한번 확인해보시고, 리팩토링 진행해주세요!
useEffect 내부의 내용 분리는 추후 도전과제로 하셔도 괜찮습니다!

2022-02-22 06:42 UTC, younuk23 commented on src/pages/JobList/JobList.js
> +  }, [params.category, params.subcategory, location.search]);
많은 노력이 들어간듯 코드처럼 보이네요 👍👍 
다만 PR 에도 적으셨듯이, useEffect가 너무 방대한 것 같습니다!
내부에 함수들 목적에 따라 분리하는 시도 해보시는게 좋을 것 같아요!

추후에 하셔도 되지만 대부분의 나중에해야지의 나중은 잘 오지 않기에 스스로 꼭 하겠다는 마음가짐으로 프로젝트 끝나고 꼭 리팩토링 해보세요!

2022-02-22 06:42 UTC, younuk23 commented on src/pages/JobList/JobList.js
> +          {positionsData.map(data => (
data라는 인자명은 이제 이세상에 없습니다. 의미가 드러나게 수정해주세요!

2022-02-22 06:42 UTC, younuk23 commented on src/Router.js
> +      {/* <Nav /> */}
이대로 머지되면 Nav가 안나올 것 같네요

2022-02-22 06:42 UTC, younuk23 commented on src/components/Buttons/FilterButton.js
> +    };
여기저기서 많이 쓰이는 로직 같은데 별도 파일로 분리해서, import 해서 쓰는게 좋겠네요!

2022-02-22 06:42 UTC, younuk23 commented on src/components/JobCard/JobCard.js
>  const JobCard = ({ data }) => {
전반적으로, data 등의 이름을 많이 사용하고 있는데 너무 추상적인 이름입니다! 좀 더 명확하도록 이름 짓는 연습을 해보시면 더 좋은 코드를 짜실 수 있을 것 같네요!

2022-02-23 02:14 UTC, younuk23 commented
남주님 리뷰 반영해주세요!

2022-02-23 02:37 UTC, jujusnake commented on src/pages/JobList/JobList.js
> +          {positionsData.map(data => (
positions로 변경하였습니다

2022-02-23 02:38 UTC, jujusnake commented on src/components/JobCard/JobCard.js
>  const JobCard = ({ data }) => {
넵 변경하였습니다!

2022-02-23 02:53 UTC, jujusnake commented on src/components/Buttons/FilterButton.js
> +    };
처음으로 분리해보네요 감사합니다!

2022-02-23 10:17 UTC, younuk23 approved these changes
LGTM 👍

2022-02-23 10:17 UTC, merged