[29기 장예지] 로그아웃 & 프로필
wecode-bootcamp-korea/29-2nd-needed-frontend pull request #18
Opened 2022-02-22 12:10 UTC by yeji0803

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그아웃
- sessionstorage에 토큰이 있을 때 토큰이 삭제됨

2. 프로필 썸네일
- 카카오 소셜 로그인시 카카오에서 프로필 사진 정보를 가져와서 nav 프로필 생성
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 여러 handler에 많은 기능을 부가할 시에 중복되어서 event가 발생되는 경우가 생기기 때문에 하나의 handler에 하나의 기능을 넣는게 좋다.

<br />

## :: 기타 질문 및 특이 사항

2022-02-23 02:25 UTC, younuk23 requested changes
고생하셨습니다 예지님 리뷰 확인 및 반영해주세요!

2022-02-23 02:25 UTC, younuk23 commented on src/pages/Login/Login.js
> +    setModalOpen(prev => !prev);
```suggestion
    modalHandler()
```

여기서 하는 일은 모달의 상태를 변경하고, 로그아웃을 한다 인 것 같네요
그러면 setModalOpen이라는 setState 함수를 바로 호출하기보다는 이미 모달을 컨트롤하기 위해 만들어둔 modalHandler 함수를 호출하는게 좋을 것 같네요!!

이렇게 하면 추후에 modal을 handling하는 로직에 변경이 생겼을때 (단순히 이름변경부터, 여러개의 state를 수정하는식으로 변경된다던가 여러 케이스가 있겠네요) modalHandler 함수 내부의 동작만 바꿔주면 되서 좀 더 변화에 유연하게 대응할 수 있습니다

2022-02-23 07:00 UTC, yeji0803 commented on src/pages/Login/Login.js
> +    setModalOpen(prev => !prev);
넵 리뷰 반영 완료했습니다~~

2022-02-24 01:53 UTC, younuk23 requested changes
고생하셨습니다 예지님!! 추가구현 구현중이라서 머지는 안하겠습니다!

2022-02-24 01:53 UTC, younuk23 commented on src/pages/Login/SignUp.js
>    const ModalHandler = () => {
camelCase로 지어주세요!

2022-02-24 01:53 UTC, younuk23 commented on src/pages/Login/Login.js
> +      <HandleModar onClick={logOutHandler}>
sessionStorage에서 getItem에서 login 여부 판단하는 로직이 여기저기서 많이 쓰이는데, 
매번 이렇게 쓰기보다 별도 함수로 추출해서 호출하는 형태로 하는게 좀 더 좋겠네요!!

그러면, 나중에 sessionStorage에서 localStorage로 바뀐다고 해도, 함수 본문 내용만 수정하는 식으로 대응할 수 있습니다!

2022-02-24 03:45 UTC, yeji0803 commented on src/pages/Login/SignUp.js
>    const ModalHandler = () => {
넵넵

2022-02-24 03:56 UTC, yeji0803 commented on src/pages/Login/Login.js
> +      <HandleModar onClick={logOutHandler}>
넵 수정하겠습니다~

2022-02-24 05:27 UTC, merged