[29기 윤남주] JobDetail 컴포넌트 구현
wecode-bootcamp-korea/29-2nd-needed-frontend pull request #5
Opened 2022-02-17 04:56 UTC by jujusnake

Add : 라이브러리 추가 - slick, 카카오 맵 API
Add : 라우팅 추가
Add : 스크립트 추가 kakaomap API + fontawesome
Add : JobDetail 컴포넌트화 + 레이아웃 작업
Add : Kakaomap 구현

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표
- 채용 상세페이지 구현
- 카카오맵 API로 움직이지 않고 zoom이 불가능한 지도 화면 구현
- Slick 라이브러리로 슬라이더 구현

<br />

## :: 구현 사항 설명
1. JobDetail 레이아웃 구현
- 좌측 컨텐츠 영역 + 우측 sticky 지원하기 창
- 최상단 이미지 슬라이더
- 하단 지도 : 주어지는 주소 문자열로 좌표를 찾아 렌더링하는 부분까지 구현

2. 지원하기 클릭 시의 창
- 개인 정보 입력 폼
- 첨부파일

<br />

## :: 성장 포인트
- 처음으로 카카오맵 API를 사용하였습니다.
- 문자열로 된 주소로 좌표를 찾는 기능까지 구현하였습니다.
- 드래그와 줌이 불가능하도록 구현하였습니다.

<br />

## :: 기타 질문 및 특이 사항
- 컴포넌트가 너무 많아지는 것 같습니다. 의견 부탁드립니다.

2022-02-18 06:00 UTC, yeonuk-hwang requested changes
고생하셨습니다 남주님 리뷰 확인 및 반영해주세요~!

2022-02-18 06:00 UTC, yeonuk-hwang commented on src/pages/JobDetail/JobDetail.js
> +        </Sub>
- 컴포넌트가 너무 많아진 것 같습니다. 지금 컴포넌트 구조가 괜찮은지 의견 부탁드립니다.
=> 지금 JobDetail 컴포넌트 구조 괜찮아보이네요 👍 오히려 이부분도isApplicationFormOpen 을 props으로 전달해서 그값에 따라서 다른것 보여주는 컴포넌트로 만들면 JobDetail 컴포넌트를 봤을때 어떻게 구성되어 있는지 알아보기 더 편할 것 같네요!

2022-02-18 06:00 UTC, yeonuk-hwang commented on src/pages/JobDetail/JobDetailApplicationForm.js
> +    }
```suggestion
    return !!(
      uploadedFile &&
      information.name &&
      information.email &&
      information.phone
    ) 
```
바로 저 값만 return 해줘도 될 것 같네요! && 연산쓰면 boolean이 아니라 truthy, falsy 값이 나오는것이 우려되서 저렇게 표현한거라면 !! 통해서 boolean으로 형변환 할 수 있습니다!

2022-02-18 06:00 UTC, yeonuk-hwang commented on src/pages/JobDetail/JobDetailApplicationForm.js
> +    }
함수 분리 깔끔하네요! 👍

2022-02-18 06:00 UTC, yeonuk-hwang commented on src/pages/JobDetail/JobDetailApplicationForm.js
> +  .sideDesc {
- styled-component를 이용해서 스타일링이 된 태그들은 해당 definition으로 이동해서 바로 스타일링을 확인이 가능한데 className으로 선언한 부분은 바로 definition으로 이동이 불가능해서 스타일링 파악하기에 어려움이 있음
- 위의 내용에 덧붙여서 className을 이용한 스타일링의 nesting depth가 깊어지는 경우에는 더 더욱 찾기가 힘들어짐
- depth가 깊어지는 경우 뿐만 아니라 1depth로도 className을 이용한 스타일 선언부가 길어지는 경우에도 해당 스타일링을 찾기 어려워짐
- 위의 사항들로 인해서 CSS in JS(styled-components 등)을 이용한 스타일링을 하는 경우에는 라이브러리 사용상 강제되는 등의 불가피한 부분을 제외하고는 className을 통한 스타일링은 최대한 지양하는게 권장됩니다. 
스타일이 필요한 경우엔 스타일드 컴포넌트 활용해주세요!

2022-02-18 06:00 UTC, yeonuk-hwang commented on src/pages/JobDetail/JobDetailApplicationForm.js
> +  .sideDesc {
- styled-component를 이용해서 스타일링이 된 태그들은 해당 definition으로 이동해서 바로 스타일링을 확인이 가능한데 className으로 선언한 부분은 바로 definition으로 이동이 불가능해서 스타일링 파악하기에 어려움이 있음
- 위의 내용에 덧붙여서 className을 이용한 스타일링의 nesting depth가 깊어지는 경우에는 더 더욱 찾기가 힘들어짐
- depth가 깊어지는 경우 뿐만 아니라 1depth로도 className을 이용한 스타일 선언부가 길어지는 경우에도 해당 스타일링을 찾기 어려워짐
- 위의 사항들로 인해서 CSS in JS(styled-components 등)을 이용한 스타일링을 하는 경우에는 라이브러리 사용상 강제되는 등의 불가피한 부분을 제외하고는 className을 통한 스타일링은 최대한 지양하는게 권장됩니다. 

스타일이 필요한 경우엔 스타일드 컴포넌트 활용해주세요!

2022-02-18 06:00 UTC, yeonuk-hwang commented on src/pages/JobDetail/Map.js
> +  }, [address]);
useEffect의 callback안에서 바깥 스코프에 있는 값들을 활용하고 있으면 dependencyArray에 넣어주는게 좋습니다. 지금은 kakao.map.services등을 사용하고 있는데 이게 디펜던시 어레이에 없어서 문제가 뜨고 있네요!

여러가지 방법이 있을 수 있는데 가장 간단한 방법은, `const {kakao} = window;`를 callback안에서 선언하는 방법이 있을 것 같네요, 이거에 관련된 내용은 useEffect 완벽가이드 라는 제목을 구글에 검색해보시면 잘 설명된 아티클이 있을겁니다. 남주님은 충분히 공부해볼 수 있을 것 같아서 한번 시도해보세요!

2022-02-18 06:13 UTC, younuk23 commented
🚨 kakao map api를 불러오는 <script> 부분의 경우 앱키를 .env에 넣으라고 하는거같은데, 추가구현으로 해도 될 부분인지 의견 부탁드립니다!

- 이런 외부 API key들을 그대로 코드상에 노출하면 보안에 위협이 될 수 있습니다.
- 이런 코드상에 유출되면 안되는 정보들은 환경변수를 통해서 관리해주는게 좋습니다
- CRA는 .env 파일을 통해서 편하게 환경변수를 설정할 수 있습니다.
- `.env`파일을 통해서 환경변수 관리해주시고 gitignore에 `.env` 파일을 등록해서 github상에 노출되지 않도록 해주세요
- 참고자료
- [Create React App 공식문서](https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env)
- 
이부분은 보안에 관련된 민감한 문제라서 .env로 환경변수로 관리하는것 바로 적용하시는 방향으로 가주세요!

2022-02-20 13:07 UTC, jujusnake commented on src/pages/JobDetail/Map.js
> +  }, [address]);
간단하게 해결되는 문제였네요!! 추천해주신 아티클 스터디도 해보겠습니다!

2022-02-21 02:45 UTC, younuk23 requested changes
고생하셨습니다 남주님
- 🚨 gitignore에 넣었는데... 그러면 다른 팀원들은 못받지 않나요? 그냥 로컬에서 env파일을 각자 다 만들어야할까요?
=> 네 gitignore에 추가해서 github상에 올라가지 않게 관리해주시고 env 파일은 팀원들이 다 각자 로컬에서 만들고 내용은 공유해주는 방식으로 진행해주시면 됩니다.
별개로, 지금 .env가 file changed에 올라와있는데, 이부분 해결해주세요! 이거 해결되면 바로 머지하겠습니다!

2022-02-21 04:04 UTC, merged