[29기 장예지] add: login layout
wecode-bootcamp-korea/29-2nd-needed-frontend pull request #6
Opened 2022-02-17 07:11 UTC by yeji0803

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 모달창으로 로그인 창 생성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입/로그인을 누르면 모달창이 실행된다.
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 모달라이브러리를 한번 사용해봤는데 스타일링하기가 어렵고 style관련 라이브러리를 또 install해야되서 간단한 모달을 만들때는
라이브러리를 사용하지 않는 것이 좋겠다고 느꼈습니다. 

<br />

## :: 기타 질문 및 특이 사항
- 현재 nav가 merge가 되지 않아서 nav와 연결된 branch를 생성할까 고민했지만 nav에 관련된 기능들이 많아서 일단은 버튼을 그냥 만들어두고 나중에 nav가 merge가 되면 수정하려고 합니다.

2022-02-18 03:37 UTC, younuk23 requested changes
- 성장포인트 너무 좋네요 👍
- 이부분도 회원가입 페이지와 마찬가지로 머지가능할 것 같습니다!

2022-02-18 03:37 UTC, younuk23 commented on src/pages/Login/Login.js
> +  const ModalHandler = () => {
```suggestion
  const modalHandler = () => {
```
특정 경우 제외하고는 camelCase로 네이밍 지어주세요!

2022-02-18 03:37 UTC, younuk23 commented on src/pages/Login/Login.js
> +          <Logo src="images/login/needed.png" alt="logo" />
```suggestion
          <Logo src="/images/login/needed.png" alt="logo" />
```
절대경로로 적어주세요! 상대경로로 지정하게 되면 path의 depth가 깊어졌을때 원하는대로 public 폴더에 접근을 하지 못합니다!

예시) 상대경로로 작성했을 시
- http://localhost:3000/main => 이경우에는 상대경로로 작성해도 public 폴더로 정상 인식해서 정상동작
- http://localhost:3000/detail/1 => 이경우에는 path의 depth가 깊어져서 상대경로로 지정하게되면 pubilc/detail 폴더안에서 찾으려고 하기 때문에 제대로 동작하지 않음.

2022-02-18 04:00 UTC, yeji0803 commented
현재 소셜로그인 기능을 지금 이 branch에서 구현중이라 로그인 기능까지 이 브런치에서 마무리 하겠습니다~

2022-02-21 02:49 UTC, younuk23 requested changes
고생하셨습니다 예지님! 
리뷰 확인 및 반영해주세요!
그리고 추가기능구현중 라벨 붙은건 본문에 질문주신 사항 관련된 내용인가요?
질문주신 부분은 실제 어떤 상황에서 발생하는지 확인을 해봐야 할 것 같아서 라운지 저나 다른 멘토분들한테 한번 질문주세요!

2022-02-21 02:49 UTC, younuk23 commented on public/index.html
> +      Kakao.init('746a759a33686fbf7cf478afc0274961');
- 이런 외부 API key들을 그대로 코드상에 노출하면 보안에 위협이 될 수 있습니다.
- 이런 코드상에 유출되면 안되는 정보들은 환경변수를 통해서 관리해주는게 좋습니다
- CRA는 .env 파일을 통해서 편하게 환경변수를 설정할 수 있습니다.
- `.env`파일을 통해서 환경변수 관리해주시고 gitignore에 `.env` 파일을 등록해서 github상에 노출되지 않도록 해주세요
- 참고자료
- [Create React App 공식문서](https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env)

2022-02-21 05:04 UTC, yeji0803 commented on public/index.html
> +      Kakao.init('746a759a33686fbf7cf478afc0274961');
넵 env 파일 만들어서 관리하겠습니다. 
기능 구현은 로그인시 프로필이 변화하는 기능을 구현하려했는데 다른 브런치에서 만드려고 합니다.
수정사항 검토 후 merge 부탁드립니다~

2022-02-21 05:51 UTC, younuk23 approved these changes

2022-02-21 05:51 UTC, merged