[29기 곽승현] Add : Company.js의 룩을 구현하고, 코드의 가독성을 위해 컴포넌트를 분리하고, 컨플릭트를 해결했습니다.
wecode-bootcamp-korea/29-2nd-needed-frontend pull request #7
Opened 2022-02-17 08:43 UTC by hyunkark

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회사 상세 페이지 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회사 상세 페이지 구현
- Jsx와 styled components를 이용해 룩 구현
- 코드의 가독성을 위해 컴포넌트 분리
- mock data를 이용해 페이지 안의 컴포넌트를 렌더링 할 수 있도록 함.
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- Rebase 도중 생기는 conflict를 해결할 수 있게 됨
  - git은 진짜 친절한 것 같다.... 에러 메시지에 나온 대로 했더니 컨플릭트 해결 되어 있었다....
- Company.js와 연결된 json파일을 수정 할 때다 터져나가는 페이지와 무수히 뜨는 에러 메시지 해결
  - 초기에 데이터를 받아와 하위 컴포넌트로 내려줄 때, 데이터 자체에 수정이 가해지면서 하위 컴포넌트로 내려질 데이터들이 계속 문제를 일으켜 에러 메시지들이 뜨는 것이었음.
  - 해결 방법: 하위 컴포넌트에서 props를 받아오는 코드 구문들을 주석 처리해 우선 상위 컴포넌트에서 제대로 데이터가 들어오는 것을 확인하고, 하위 컴포넌트에서 주석을 풀어 제대로 데이터가 들어오는지 확인한다.

<br />

## :: 기타 질문 및 특이 사항
- 추가 구현 사항 : 이미지를 클릭하면 이미지가 확대되면서 모달 창으로 뜨는 기능

2022-02-18 03:33 UTC, younuk23 requested changes
고생하셨습니다 리뷰 확인 및 반영해주세요~!

2022-02-18 03:33 UTC, younuk23 commented on src/pages/Company/Company.js
> +      .then(data => setCompanyData(data));
```suggestion
      .then(([data]) => setCompanyData(data));
```
0번째 아이템만 필요한거라면 위와 같이 표현해도 될 것 같네요!

2022-02-18 03:33 UTC, younuk23 commented on src/pages/Company/Company.js
> +const CompanyBody = styled(Makecenter)`
상속 잘 활용하셨네요 👍

2022-02-18 03:33 UTC, younuk23 commented on src/pages/Company/components/Card.js
> +  return (
```suggestion
  const { id, name, compensation } = data;

  return (
```
다른 문맥들끼리는 공백을 통해서 가독성에 신경써주세요

2022-02-18 03:33 UTC, younuk23 commented on src/pages/Company/components/Chip.js
> +      </ThemeProvider>
index.js에서 GlobalStyle, ThemeProvider 적용하고 있는 것 같은데 다시 주입해주신 이유가 있나요?

2022-02-18 03:33 UTC, younuk23 commented on src/pages/Company/components/CompanyAside.js
> +          companyTags.map((data, idx) => {
```suggestion
        {companyTags?.map((data, idx) => {
```
***
optional chaining 문법 사용하면 동일한 동작을 조금 더 간결하게 표현할 수 있습니다.
어떻게 동작하는지 공부하고 이해해보시고 적용해보세요~!
***
그리고 data라는 변수명보다는 의미가 잘 드러나는 변수명으로 활용해주세요!

2022-02-18 03:33 UTC, younuk23 commented on src/pages/Company/components/CompanyHead.js
> +  .logo {
- styled-component를 이용해서 스타일링이 된 태그들은 해당 definition으로 이동해서 바로 스타일링을 확인이 가능한데 className으로 선언한 부분은 바로 definition으로 이동이 불가능해서 스타일링 파악하기에 어려움이 있음
- 위의 내용에 덧붙여서 className을 이용한 스타일링의 nesting depth가 깊어지는 경우에는 더 더욱 찾기가 힘들어짐
- depth가 깊어지는 경우 뿐만 아니라 1depth로도 className을 이용한 스타일 선언부가 길어지는 경우에도 해당 스타일링을 찾기 어려워짐
- 위의 사항들로 인해서 CSS in JS(styled-components 등)을 이용한 스타일링을 하는 경우에는 라이브러리 사용상 강제되는 등의 불가피한 부분을 제외하고는 className을 통한 스타일링은 최대한 지양하는게 권장됩니다. 
스타일이 필요하신 경우 스타일드 컴포넌트 선언해서 활용해주세요!

2022-02-18 03:33 UTC, younuk23 commented on src/pages/Company/components/CompanyInfo.js
> +  let joinedDesc = companyDesc.join(' ');
```suggestion
  const joinedDesc = companyDesc.join(' ');
```
let은 반드시 재할당이 필요한 경우에만 활용해주세요!

2022-02-18 03:33 UTC, younuk23 commented on src/pages/Company/components/CompanyInfo.js
> +              {toggle ? '접기' : '더보기'}{' '}
```suggestion
              {toggle ? '접기' : '더보기'}
```
formatting 과정에서 불필요하게 들어가는 부분들 꼼꼼하게 잘 확인해주세요!

2022-02-21 02:51 UTC, younuk23 commented
승현님 리뷰 반영해주세요~!

2022-02-21 03:07 UTC, hyunkark commented on src/pages/Company/Company.js
> +      .then(data => setCompanyData(data));
리뷰 감사합니다! 수정해서 다시 푸쉬 할 수 있도록 하겠습니다!

2022-02-21 03:07 UTC, hyunkark commented on src/pages/Company/components/Chip.js
> +      </ThemeProvider>
index.js에서 GlobalStyle, ThemeProvider를 적용하고 있다는 것을 모르고 다시 선언했습니다... 이 부분은 제가 작업한 모든 컴포넌트에서 동일하게 실수한 부분인지라 수정하도록 하겠습니다!

2022-02-22 06:20 UTC, merged

2022-02-22 06:21 UTC, younuk23 commented
LGTM 👍